from enum import Enum


class QuestionnaireOutcomeCodes(Enum):
    NOT_STARTED_0 = 0
    WEB_NUDGED_120 = 120
    APPOINTMENT_300 = 300
    NON_CONTACT_310 = 310
    PHONE_NO_REMOVED_BY_TO_320 = 320
    REFUSAL_HARD_460 = 460
    REFUSAL_SOFT_461 = 461
    INELIGIBLE_NO_TRACE_OF_ADDRESS_510 = 510
    INELIGIBLE_VACANT_540 = 540
    INELIGIBLE_NON_RESIDENTIAL_551 = 551
    INELIGIBLE_INSTITUTION_560 = 560
    INELIGIBLE_SECOND_OR_HOLIDAY_HOME_580 = 580
    WRONG_ADDRESS_640 = 640

class QuestionnaireOutcomeCodesFRS(Enum):
    CONTACT_MADE_AT_ADDRESS_NO_CONTACT_WITH_SAMPLED_HOUSEHOLD_MULTI = 320
    CONTACT_WITH_SAMPLED_HOUSEHOLD_NO_CONTACT_WITH_RESPONSIBLE_RESIDENT = 330
    HQ_OFFICE_REFUSAL_GENERAL = 410
    MULTI_INFORMATION_REFUSED_NO_OF_HOUSEHOLDS_AT_ADDRESS = 420
    REFUSAL_AT_INTRODUCTION_BEFORE_INTERVIEW_BY_ADULT_HOUSEHOLD_MEMBER = 431
    REFUSAL_AT_INTRODUCTION_BEFORE_INTERVIEW_BY_PROXY = 432
    REFUSAL_DURING_INTERVIEW_HRP_BU_MEMBER_REFUSED_TO_COMPLETE_INTERVIEW = 441
    REFUSAL_DURING_INTERVIEW_12_PLUS_DKS_OR_REFUSALS_IN_HHLD_SECTION_HRP_BU = 442
    BROKEN_APPOINTMENT_NO_RE_CONTACT = 450
    REFUSAL_HARD_460 = 460
    REFUSAL_SOFT_461 = 461
    INELIGIBLE_NO_TRACE_OF_ADDRESS_510 = 510
    ILL_AT_HOME_DURING_SURVEY_PERIOD = 512
    AWAY_IN_HOSPITAL_DURING_SURVEY_PERIOD = 522
    PHYSICALLY_MENTALLY_UNABLE_INCOMPETENT = 532
    INELIGIBLE_VACANT_540 = 540
    LANGUAGE_DIFFICULTIES = 542
    INELIGIBLE_NON_RESIDENTIAL_551 = 551
    INELIGIBLE_INSTITUTION_560 = 560
    INELIGIBLE_SECOND_OR_HOLIDAY_HOME_580 = 580
    NOT_ISSUED_TO_INTERVIEWER_OFFICE_APPROVAL_NEEDED = 611
    ISSUED_BUT_NOT_ATTEMPTED_OFFICE_APPROVAL_NEEDED = 612
    INACCESSIBLE = 620
    UNABLE_TO_LOCATE_ADDRESS = 630
    WRONG_ADDRESS_640 = 640
    UNKNOWN_WHETHER_RESIDENTIAL_HOUSING_INFORMATION_REFUSED = 641
    UNKNOWN_WHETHER_RESIDENTIAL_HOUSING_NO_CONTACT_WITH_KNOWLEDGEABLE_PERSON = 642
    RESIDENTIAL_ADDRESS_UNKNOWN_IF_ELIGIBLE_HOUSEHOLD_INFORMATION_REFUSED = 651
    RESIDENTIAL_ADDRESS_UNKNOWN_IF_ELIGIBLE_HOUSEHOLD_NO_CONTACT_WITH_KNOWLEDGEABLE_PERSON = 652
    OTHER_UNKNOWN_ELIGIBILITY_OFFICE_APPROVAL_NEEDED = 670
    NOT_YET_BUILT_UNDER_CONSTRUCTION = 710
    DEMOLISHED_DERELICT = 720
    VACANT_EMPTY = 730
    NON_RESIDENTIAL_ADDRESS = 740
    ADDRESS_OCCUPIED_NO_RESIDENT_HOUSEHOLD = 750
    COMMUNAL_ESTABLISHMENT_INSTITUTION = 760
    DWELLING_OF_FOREIGN_SERVICE_PERSONNEL_DIPLOMATS = 771
    ALL_RESIDENTS_UNDER_16 = 772
    OTHER_RESIDENT_HOUSEHOLD_NO_ELIGIBLE_RESIDENTS = 773
    DIRECTED_NOT_TO_SAMPLE_AT_ADDRESS = 781
    NOT_TO_INTERVIEW_INSTRUCTS_SCOTTISH_PRE_SELECTION_SHEET = 782
    HOUSEHOLD_LIMIT_ON_QUOTA_REACHED_MAXIMUM_OF_4_EXTRA_HOUSEHOLDS = 783
    OTHER_OFFICE_APPROVAL_NEEDED = 790
