[tool.poetry]
name = "blaise_totalmobile_services"
version = "1.0.0"
description = ""
authors = ["Blaise Team"]

[tool.poetry.dependencies]
python = "^3.13"
grpcio = "^1.70.0"
greenlet = "^3.0.0"
protobuf = "5.29.6"
requests = "^2.33.1"
blaise-restapi = {git = "https://github.com/ONSdigital/blaise-api-python-client.git", rev = "v1.0.2"}
google-auth = "^2.40.0"
google-cloud-pubsub = "^2.37.0"
google-cloud-tasks = "^2.22.0"
Flask = "^3.1.3"
config = "^0.5.1"
python-dotenv = "^1.2.2"
pytest = "^9.0.3"
Flask-HTTPAuth = "^4.8.1"
phonenumbers = "^8.12.46"
google-cloud-datastore = "^2.21.0"
google-cloud-logging = "^3.12.0"
dataclasses-json = "^0.6.5"
dataclass-wizard = "^0.22.1"
typing-extensions = "^4.12.2"
setuptools = "82.0.1"
pytest-mock = "^3.15.1"
behave-html-formatter = "^0.9.10"
urllib3 = "2.6.3"
werkzeug = "3.1.6"
pyasn1 = "^0.6.3"
marshmallow = "3.26.2"

[tool.poetry.group.dev.dependencies]
types-setuptools = "^75.8.0.20250210"
black = "^26.3.1"
pytest = "^9.0.3"
python-dotenv = "^1.2.2"
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^1.17.1"
types-requests = "^2.27.11"
types-Flask = "^1.1.6"
pytest-cov = "^3.0.0"
requests-mock = "^1.9.0"
Flask = "^3.1.3"
Flask-SQLAlchemy = "^2.5.1"
SQLAlchemy = "^1.4.32"
phonenumbers = "^8.12.46"
mocker = "^1.1.1"
responses = "^0.20.0"
requests-mock-flask = "^2022.4.3"
google-cloud = "^0.34.0"
google-cloud-datastore = "^2.7.1"
behave = "^1.2.6"
types-protobuf = "^3.19.22"
types-pytest-lazy-fixture = "^0.6.3"

[tool.isort]
multi_line_output = "3"
include_trailing_comma = "True"
line_length = "88"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[flake8]
max-line-length = 120
